apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      taskSpec:
        metadata: {}
        spec: null
        stepTemplate:
          computeResources:
            requests:
              cpu: 400m
              memory: 512Mi
          env:
          - name: NPM_CONFIG_USERCONFIG
            value: /tekton/home/npm/.npmrc
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/javascript/release.yaml@versionStream
          volumeMounts:
          - mountPath: /tekton/home/npm
            name: npmrc
          workingDir: /workspace/source
        steps:
        - computeResources: {}
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
        - computeResources: {}
          name: next-version
        - computeResources: {}
          name: jx-variables
        - computeResources: {}
          name: build-npm-install
        - computeResources: {}
          name: build-npm-test
        - computeResources: {}
          name: build-container-build
        - computeResources: {}
          name: promote-changelog
        - computeResources: {}
          name: promote-helm-release
        - computeResources: {}
          name: promote-jx-promote
        volumes:
        - name: npmrc
          secret:
            optional: true
            secretName: npmrc
  taskRunTemplate:
    serviceAccountName: tekton-bot
  timeouts:
    pipeline: 240h0m0s
status: {}
