apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: chart
      taskSpec:
        metadata: {}
        spec: null
        stepTemplate:
          computeResources: {}
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go-plugin/release.yaml@versionStream
          workingDir: /workspace/source
        steps:
        - computeResources: {}
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
        - computeResources: {}
          image: gcr.io/jenkinsxio/use-different0-image:1.0.42
          name: next-version
          script: |
            #!/usr/bin/env bash
            VERSION=$(jx-release-version)
            echo $VERSION > VERSION
        - computeResources: {}
          name: jx-variables
        - computeResources: {}
          name: release-binary
        - computeResources: {}
          name: build-and-push-image
        - computeResources: {}
          image: gcr.io/kaniko-project/executor:debug-v1.3.0
          name: build-and-push-image-bdd
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=/workspace/source/Dockerfile-bdd --destination=gcr.io/$DOCKER_REGISTRY_ORG/jx-bdd:$VERSION --destination=gcr.io/$DOCKER_REGISTRY_ORG/jx-bdd:latest
        - computeResources: {}
          image: gcr.io/kaniko-project/executor:debug-v1.3.0
          name: build-and-push-image-go
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=/workspace/source/Dockerfile-go --destination=gcr.io/$DOCKER_REGISTRY_ORG/jx-go:$VERSION --destination=gcr.io/$DOCKER_REGISTRY_ORG/jx-go:latest
        - computeResources: {}
          image: gcr.io/kaniko-project/executor:debug-v1.3.0
          name: build-and-push-image-go-maven
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=/workspace/source/Dockerfile-go-maven --destination=gcr.io/$DOCKER_REGISTRY_ORG/jx-go-maven:$VERSION --destination=gcr.io/$DOCKER_REGISTRY_ORG/jx-go-maven:latest
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=gcr.io/$DOCKER_REGISTRY_ORG/$REPO_NAME:$VERSION
        - computeResources: {}
          name: chart-docs
        - computeResources: {}
          name: release-chart
        - computeResources: {}
          name: changelog
        - computeResources: {}
          name: upload-binaries
        - computeResources: {}
          image: google/cloud-sdk:slim
          name: build-and-push-image-multi
          script: |
            #!/bin/bash
            source .jx/variables.sh
            gcloud builds submit --config cloudbuild.yaml --project jenkinsxio --substitutions=_VERSION="$VERSION"
        - computeResources: {}
          name: promote-release
  taskRunTemplate:
    serviceAccountName: tekton-bot
  timeouts:
    pipeline: 240h0m0s
status: {}
