apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
    - urls:
        - https://github.com/jenkins-x/jx
      changes:
        - regex:
            pattern: |
              \s+PipelineVersion = "(.*)"
            files:
              - "pkg/plugins/versions.go"
    - urls:
      - https://github.com/jenkins-x-plugins/jx-build-controller
      - https://github.com/jenkins-x/jx-pipelines-visualizer
      changes:
      - regex:
          pattern: |
            github.com/jenkins-x-plugins/jx-pipeline v(.*)
          files:
          - "go.mod"
      - command:
          name: go
          args:
          - mod
          - tidy
