apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
      - name: from-build-pack
        computeResources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go/pullrequest.yaml@versionStream
            name: ""
            computeResources:
              # override limits for all containers here
              limits: {}
            workingDir: /workspace/source
          steps:
            - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
              name: ""
              computeResources: {}
            - name: jx-variables
              computeResources:
                # override requests for the pod here
                requests:
                  cpu: 400m
                  memory: 600Mi
            - name: hello-world
              image: golang:1.19
              script: |
                  #!/usr/bin/env sh
                  echo "hello world"
            - name: build-make-linux
              computeResources: {}
            - name: check-registry
              computeResources: {}
            - name: build-container-build
              computeResources: {}
            - name: promote-jx-preview
              computeResources: {}
  taskRunTemplate:
    serviceAccountName: tekton-bot
  timeouts:
    pipeline: 1h0m0s
status: {}
