apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      taskSpec:
        metadata: {}
        spec: null
        stepTemplate:
          computeResources: {}
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/javascript/release.yaml@myversionstreamref
        steps:
        - computeResources: {}
          image: gcr.io/jenkinsxio/jx-release-version:2.2.5
          name: next-version
          script: |
            #!/usr/bin/env sh
            jx-release-version > VERSION
        - computeResources: {}
          name: jx-variables
        - computeResources: {}
          name: build-npm-install
        - computeResources: {}
          name: build-npm-test
        - computeResources: {}
          name: check-registry
        - computeResources: {}
          name: build-container-build
        - computeResources: {}
          name: promote-changelog
        - computeResources: {}
          name: promote-helm-release
        - computeResources: {}
          name: promote-jx-promote
  taskRunTemplate: {}
status: {}
