apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      taskSpec:
        metadata: {}
        spec: null
        stepTemplate:
          computeResources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - computeResources: {}
          image: gcr.io/jenkinsxio/jx-boot:3.1.156
          name: jx-variables
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - computeResources: {}
          image: node:12-slim
          name: build-npm-install
          script: |
            #!/bin/sh
            npm install
        - computeResources: {}
          image: node:12-slim
          name: build-npm-test
          script: |
            #!/bin/sh
            CI=true DISPLAY=:99 npm test
        - computeResources: {}
          image: gcr.io/kaniko-project/executor:debug-v1.3.0
          name: build-container-build
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
        - computeResources: {}
          image: gcr.io/jenkinsxio/jx-preview:0.0.143
          name: promote-jx-preview
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh
            jx preview create
  taskRunTemplate:
    serviceAccountName: tekton-bot
  timeouts:
    pipeline: 240h0m0s
status: {}
