apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - computeResources: {}
      name: from-build-pack
      taskSpec:
        metadata: {}
        stepTemplate:
          computeResources:
            requests:
              cpu: 400m
              memory: 512Mi
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/javascript/pullrequest.yaml@versionStream
          name: ""
          workingDir: /workspace/source
        steps:
        - computeResources: {}
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
        - computeResources: {}
          name: jx-variables
        - computeResources: {}
          name: build-npm-install
        - computeResources: {}
          name: build-npm-test
        - computeResources: {}
          name: build-container-build
        - computeResources: {}
          name: promote-jx-preview
  taskRunTemplate:
    serviceAccountName: tekton-bot
  timeouts:
    pipeline: 240h0m0s
