apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: jx-pipeline-release
      resources: {}
      timeout: 4h
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go-plugin/release.yaml@versionStream
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          resources: {}
        - name: jx-variables
          resources:
            requests:
              cpu: 1400m
              memory: 600Mi
        - image: golang:1.24.4@sha256:d1db785fb37feb87d9140d78ed4fb7c75ee787360366a9c5efe39c7a841a0277
          name: coverage-report
          resources: {}
          script: |
            #!/bin/sh
            . .jx/variables.sh
            apk add --update make bash curl coreutils git
            make test-coverage
            curl -s https://codecov.io/bash -o codecov.sh
            bash codecov.sh -Z -B ${PULL_BASE_REF} -C ${PULL_BASE_SHA} -f ./build/reports/cover.txt
          env:
          - name: CODECOV_TOKEN
            valueFrom:
              secretKeyRef:
                name: codecov-jx-plugins
                key: token
                optional: true
        - name: release-binary
          resources: {}
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/build-scan-push/build-scan-push.yaml@versionStream
          name: build-container
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/build-scan-push/build-scan-push.yaml@versionStream
          name: push-container
        - name: chart-docs
          resources: {}
        - image: ghcr.io/jenkins-x/jx-boot:3.2.304
          name: release-chart
          resources: {}
          script: |
            #!/usr/bin/env sh
            # Not sure why we need this in jx-pipeline release pipelines
            cp /tekton/creds/.git-credentials /tekton/home/.git-credentials
            source .jx/variables.sh
            jx gitops helm release
        - name: changelog
          resources: {}
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/supply-chain-security/task.yaml@versionStream
          name: download-syft
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/supply-chain-security/task.yaml@versionStream
          name: build-and-push-sbom
          resources: {}
        - name: cleanup-image-tar
          image: alpine:3.16
          resources: {}
          script: |
            #!/bin/sh
            rm -f /workspace/source/image.tar
        - name: upload-binaries
          resources: {}
        - name: promote-release
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 4h
status: {}
